
version: '3.7'
services:
  server:
    container_name: 'server'
    build:
      context: .
    ports:
    - '3000:80'
    # command: ['sh', '-c', 'sleep 600']
    volumes:
    - './:/usr/app'
    - /usr/app/node_modules
