
version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
    - '1080:80' 
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
    - "3000:80"
